quadratic_sieve_openmp: main.cpp Quadratic-Sieve.cpp
	g++ main.cpp Quadratic-Sieve.cpp -Wall -O3 -std=c++17 -lgmp -lgmpxx -o quadratic_sieve_openmp -fopenmp

clean:
	rm -f *.o *.out quadratic_sieve_openmp

